# Generated by Django 3.1.14 on 2022-01-15 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_public_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_url_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
