# Generated by Django 3.1.4 on 2022-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
    ]
