# Generated by Django 3.1.14 on 2022-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220114_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.AddField(
            model_name='movieseen',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
