# Generated by Django 3.1.14 on 2022-01-15 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20220115_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecomparision',
            unique_together={('user', 'better_movie', 'worse_movie')},
        ),
        migrations.AlterIndexTogether(
            name='movieseen',
            index_together={('user', 'movie')},
        ),
    ]
