# Generated by Django 3.1.14 on 2022-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220115_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseen',
            name='last_checked_movie_index',
            field=models.IntegerField(default=0),
        ),
    ]
